### ISSUE TITLE
add not logging history option

### ISSUE THREAD

**Issue by matyaskopp** [ufal/perl-pmltq-server#40]
add option not logging history.
For PML-TQ cli client should be default to avoid huge history file.

**Comment by dan-zeman** [comment]
And maybe it should be possible to set the desired size of the history log. If the limit is reached, the oldest query is discarded so that the newest can be logged. If an old query is reused, it is moved to the top of the history (and farther from the garbage can).

"Not logging" would equal to maxSize = 0. If it is viable, one could still set unlimited history by maxSize = -1 or something. But the default could be something like 50 even for the web application.

**Comment by matyaskopp** [comment]
related to https://github.com/ufal/perl-pmltq-web/issues/94

"Not logging" (`nohistory`) option is send with query in json. (https://github.com/ufal/perl-pmltq-server/commit/57897141a9797b1e745337b9c2ea4526712e6bd5) 

I have been testing euler performance and generated history file with almost 5000 queries - the web interface has been useless. The only way to fixed this was deleting all query records directly from database.

For the beginning I will add history query record limit common for all users. 50 sounds usable.
